name: Heroku Deploy

on:
  push:
    branches:
    - workflow-testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: main 
      - name: deploy
        run: |
          sudo apt-get update
          sudo apt-get install ruby-dev
          sudo gem install dpl
          sudo dpl --provider=heroku --app=ppl-fe --api_key=77fcdb86-b77a-4f2e-85db-a0de460b030d